
package com.revature.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CatHouseImplService", targetNamespace = "http://service.revature.com/", wsdlLocation = "http://ec2-54-165-93-229.compute-1.amazonaws.com:8080/CatSoapService/CatHouse?wsdl")
public class CatHouseImplService
    extends Service
{

    private final static URL CATHOUSEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATHOUSEIMPLSERVICE_EXCEPTION;
    private final static QName CATHOUSEIMPLSERVICE_QNAME = new QName("http://service.revature.com/", "CatHouseImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ec2-54-165-93-229.compute-1.amazonaws.com:8080/CatSoapService/CatHouse?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATHOUSEIMPLSERVICE_WSDL_LOCATION = url;
        CATHOUSEIMPLSERVICE_EXCEPTION = e;
    }

    public CatHouseImplService() {
        super(__getWsdlLocation(), CATHOUSEIMPLSERVICE_QNAME);
    }

    public CatHouseImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CATHOUSEIMPLSERVICE_QNAME, features);
    }

    public CatHouseImplService(URL wsdlLocation) {
        super(wsdlLocation, CATHOUSEIMPLSERVICE_QNAME);
    }

    public CatHouseImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CATHOUSEIMPLSERVICE_QNAME, features);
    }

    public CatHouseImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatHouseImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CatHouse
     */
    @WebEndpoint(name = "CatHouseImplPort")
    public CatHouse getCatHouseImplPort() {
        return super.getPort(new QName("http://service.revature.com/", "CatHouseImplPort"), CatHouse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CatHouse
     */
    @WebEndpoint(name = "CatHouseImplPort")
    public CatHouse getCatHouseImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.revature.com/", "CatHouseImplPort"), CatHouse.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATHOUSEIMPLSERVICE_EXCEPTION!= null) {
            throw CATHOUSEIMPLSERVICE_EXCEPTION;
        }
        return CATHOUSEIMPLSERVICE_WSDL_LOCATION;
    }

}
