
package com.revature.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CatHouse", targetNamespace = "http://service.revature.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CatHouse {


    /**
     * 
     * @return
     *     returns java.util.List<com.revature.service.Cat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://service.revature.com/", className = "com.revature.service.GetAllCats")
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.GetAllCatsResponse")
    public List<Cat> getAllCats();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws TomCatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCat", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddCat")
    @ResponseWrapper(localName = "addCatResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddCatResponse")
    public String addCat(
        @WebParam(name = "arg0", targetNamespace = "")
        Cat arg0)
        throws TomCatException_Exception
    ;

}
